export const SELECT_TOOL ="SELECT_TOOL";
export const CHANGE_SIZE ="CHANGE_SIZE";
export const CHANGE_COLOR="CHANGE_COLOR";
export const CHANGE_IMAGE="CHANGE_IMAGE";
export const RESET_CANVAS="RESET_CANVAS";
export const SAVE_CANVAS="SAVE_CANVAS";
